kind: Secret
apiVersion: v1
metadata:
  name: git-auth-token
type: Opaque
stringData:
  .gitconfig: |
    [credential "https://github.com"]
      helper = store
  .git-credentials: |
    https://<user>:<pass>@github.com
